title: The Bog of All THings
author: M. J. Ray
email: mray912@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Be a life lon learner.  Let's talk about all the things that need to be talked about.

# social links
twitter_username: mray912
github_username:  mray912

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
